config/routes.rb
Rails.application.routes.draw do
  resources :proposals do
    resources :comments
    resources :votes

    member do 
      post :upvote
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  
  root to: "sessions#new"

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
 belongs_to :proposal
 belongs_to :user

 validates :body, presence: true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :proposal

  validates :name, presence: true
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  has_many :user_proposals
  has_many :users, through: :user_proposals
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  def self.by_votes
    Proposal.all.sort { |a, b| b.votes.count <=> a.votes.count }
  end
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
 # users.password_hash in the database is a :string
 has_many :user_proposals
 has_many :proposals, through: :user_proposals
 has_many :votes, dependent: :destroy
 has_many :comments, dependent: :destroy


 include BCrypt

 def password
 	@password ||= Password.new(password_hash)
 end

 def password=(new_password)
 	@password = Password.create(new_password)
 	self.password_hash = @password
 end

 def authenticate(input_password)
 	self.password == input_password
 end
end

app/models/user_proposal.rb
class UserProposal < ApplicationRecord
  belongs_to :user
  belongs_to :proposal
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :proposal

  # validates :user, uniqueness: { scope: :comment,
                                    # message: "User can only vote on this comment one time" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	def current_user
		@current_user ||= User.find(session[:id]) if session[:id]
	end
	helper_method :current_user

	def authorize
		redirect_to '/login' unless current_user
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    comment = Comment.create(comment_params)
    proposal = Proposal.find(params[:proposal_id])
    proposal.comments << comment
    current_user.comments << comment
    redirect_to proposal_path(proposal)
  end

private

  def comment_params
    params.require(:comment).permit(:comment, :body)
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  def index
    @proposals = Proposal.by_votes
  end

  def show
    @proposal = Proposal.find(params[:id])
  end

  def new
    @proposal = Proposal.new
  end

  def edit
    @proposal = Proposal.find(params[:id])
  end

  def create
    @proposal = Proposal.new(proposal_params)

    if @proposal.save
      redirect_to @proposal
    else
      render 'new'
    end
  end

  def update
    @proposal = Proposal.find(params[:id])

    if @proposal.update(proposal_params)
      redirect_to @proposal
    else
      render 'edit'
    end
  end

  def upvote
    @proposal = Proposal.find(params[:id])
    vote = Vote.new(proposal_id: @proposal.id, user_id: current_user.id)

    # vote = Vote.find_by(proposal_id: @proposal.id, user_id: current_user.id)
    if vote.save
      redirect_to(proposals_path)
    else
      @errors = "You can only vote once!"
      render 'show'
    end
  end

private
  def proposal_params
    params.require(:proposal).permit(:title, :abstract, :intro, :hypothesis, :exp_method, :date_start, :date_end, :status)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		# session.clear
	end

	def create
		user = User.find_by_email(params[:email]) if User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
			session[:id] = user.id
			redirect_to '/proposals'
		else
			@errors = ["Login incorrect. Email or password was not entered correctly."]
			redirect_to '/'
		end
	end

	def destroy
		session[:id] = nil
		redirect_to '/'
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		# session.clear
		@user = User.new
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		if params[:user][:password] != params[:user][:password_confirmation]
			@errors = ["ERROR: Passwords Don't Match!"]
			redirect_to '/'
		else
			user = User.new(user_params)
			if user.save
				session[:id] = user.id
				redirect_to '/proposals'
			else
				redirect_to '/signup'
			end
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :email, :password, :role)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>LabTrakk</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<div class="header">
		<%= link_to "LabTrakk", '/proposals' %> |
		<% if current_user %>
		Signed in as <a href="/users/<%=current_user.id %>"><%= current_user.name.capitalize %></a> | <%= link_to "Logout", '/logout' %> | <%= link_to "Create New Proposal", new_proposal_path %>
		<% else %>
		<%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
		<% end %>
	</div>
	<%= yield %>
</body>
</html>

app/views/proposals/edit.html.erb
<div class="index-container">
<div class="form-container">
  <h1>Edit</h1>

  <%= form_for :proposal, url: proposals_path do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title, :value => @proposal.title %>
    </p>

    <p>
      <%= f.label :abstract %><br>
      <%= f.text_area :abstract, :value => @proposal.abstract %>
    </p>

    <p>
      <%= f.label :intro %><br>
      <%= f.text_area :intro, :value => @proposal.intro %>
    </p>

    <p>
      <%= f.label :hypothesis %><br>
      <%= f.text_area :hypothesis, :value => @proposal.hypothesis %>
    </p>

    <p>
      <%= f.label :exp_method %><br>
      <%= f.text_area :exp_method, :value => @proposal.exp_method %>
    </p>

    <p>
      <%= f.label :date_start %><br>
      <%= f.date_field :date_start, :value => @proposal.date_start %>
    </p>

    <p>
      <%= f.label :date_end %><br>
      <%= f.date_field :date_end, :value => @proposal.date_end %>
    </p>

  <div class="submit">
    <p>
      <%= f.submit %>
    </p>
  </div>
  <% end %>
</div>
</div>

app/views/proposals/index.html.erb
<div class="index-container">
	<div class="form-container">
		<h2>Proposals</h2>
		<% @proposals.each do |proposal| %>
			<div class="form-row">
				Title
			</div>
			<label for="title" id="title"><a href="/proposals/<%= proposal.id %>"><%= proposal.title %></a></label>
			<div class=vote-count>
			 <p>Vote Count: <%= proposal.votes.count %></p>
			</div>
			<div class="form-row">
				Abstract
			</div>
			<label for="abstract"><%= proposal.abstract %></label>
			<div class="form-row">
				Intro
			</div>
			<label for="intro"><%= proposal.intro %></label>
			<div class="form-row">
				Status
			</div>
			<label for="intro" id="intro"><%= proposal.status %></label>
		<% end %>
	</div>
</div>

app/views/proposals/new.html.erb
<div class="index-container">

<div class="form-container">
  <h1>Create Proposal Here</h1>

  <%= form_for :proposal, url: proposals_path do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :abstract %><br>
      <%= f.text_area :abstract %>
    </p>

    <p>
      <%= f.label :intro %><br>
      <%= f.text_area :intro %>
    </p>

    <p>
      <%= f.label :hypothesis %><br>
      <%= f.text_area :hypothesis %>
    </p>

    <p>
      <%= f.label :method %><br>
      <%= f.text_area :exp_method %>
    </p>

    <p>
      <%= f.label :date_start %><br>
      <%= f.date_field :date_start %>
    </p>

    <p>
      <%= f.label :date_end %><br>
      <%= f.date_field :date_end %>
    </p>

  <div class="submit">
    <p>
      <%= f.submit %>
    </p>
  </div>
  <% end %>
</div>
</div>

app/views/proposals/show.html.erb
<div class="index-container">

  <div class="form-container">
    <h1>Proposal</h1><br>
    <div class="form-row">
      Title:
    </div>
    <label for="title"><%= @proposal.title %> </label><br>
    <div class="form-row">
      Abstract:
    </div>
    <label for="abstract"> <%= @proposal.abstract %> </label><br>
    <div class="form-row">
      Introduction:
    </div>
    <label for="intro"> <%= @proposal.intro%> </label><br>
    <div class="form-row">
      Hypothsis:
    </div>
    <label for="hypothesis"> <%= @proposal.hypothesis %> </label><br>
    <div class="form-row">
      Method:
    </div>
    <label for="exp_method"> <%= @proposal.exp_method %> </label><br>
    <div class="form-row">
      Date start:
    </div>
    <label for="date_start"> <%= @proposal.date_start %>: </label><br>
    <div class="form-row">
      Date end:
    </div>
    <label for="date_end"> <%= @proposal.date_end %> </label><br>

    <%= link_to 'Edit form', edit_proposal_path(@proposal) %>


    <h2>Add a comment:</h2>
    <%= form_for([@proposal, @proposal.comments.build]) do |f| %>
    <p>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
    <% end %>
    <br>

		<% @proposal.comments.each do |comment| %>
		  <div class=commment>
        <%= comment.body %>
      </div>
		<% end %>

		<%= button_to 'Vote', upvote_proposal_path(@proposal), method: :post %>
  </div>
</div>

app/views/users/index.html.erb
<div class="index-container">
  <h1>Welcome to LabTrakk</h1>

  <div class="form-container">
    <h2>Login</h2>
    <%= form_for :session, url: '/login' do |f| %>
      <div class="form-row">
        <label for="email"> Email: </label> <p class="text-field"> <%= f.text_field :email %> </p>
      </div>
      <div class="form-row">
        <label for="password"> Password: </label> <p class="text-field"> <%= f.password_field :password %> </p>
      </div>
      <%= f.submit "Submit" %>

    <% end %>
  </div>

  <div class="form-container">
    <h2>Registration </h2>
    <%= form_for :user, url: '/users' do |f| %>

      <div class="form-row">
        <label for="name"> Name: </label> <p class="text-field"> <%= f.text_field :name %> </p>
      </div>
      <div class="form-row">
        <label for="email"> Email: </label> <p class="text-field"> <%= f.text_field :email %> </p>
      </div>
      <div class="form-row">
        <label for="password"> Password: </label> <p class="text-field"> <%= f.password_field :password %> </p>
      </div>
      <div class="form-row">
        <label for="password_confirmation"> Password Confirmation: </label> <p class="text-field"> <%= f.password_field :password_confirmation %> </p>
      </div>
      <%= f.submit "Submit" %>

    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="index-container">


  <div class="form-container">
    <h1>Create account</h1>
    <%= form_for :user, url: '/users' do |f| %>

    <div class="form-row">
      <label for="name"> Name: </label> <%= f.text_field :name %>
    </div>
    <div class="form-row">
      <label for="email"> Email: </label> <%= f.text_field :email %>
    </div>
    <div class="form-row">
      <label for="password"> Password: </label> <%= f.password_field :password %>
    <div class="form-row">
    </div>
    <div class="form-row">
      <label for="password"> Password Confirmation: </label> <%= f.password_field :password_confirmation %>
    </div>

    <div class="submit">
      <%= f.submit "Register" %>
    </div>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="index-container">
	<div class="form-container">
<h1>Welcome!</h1><br><br>

<div class="user-page">
    <%= link_to 'List of proposals', proposals_path %>
    	
</div>
</div>
</div>